-- Tracker Signature Database — Initial Seed
-- 30+ services common on Indian websites. Curated April 2026.
-- Re-runnable: ON CONFLICT (service_slug) DO UPDATE

insert into tracker_signatures (service_name, service_slug, category, detection_rules, data_locations, is_functional) values
-- Analytics
('Google Analytics 4', 'google-analytics-4', 'analytics',
  '[{"type":"script_src","pattern":"googletagmanager.com/gtag/js","confidence":0.95},{"type":"script_src","pattern":"google-analytics.com/analytics.js","confidence":0.95},{"type":"resource_url","pattern":"google-analytics.com/g/collect","confidence":0.98}]'::jsonb,
  array['US'], false),
('Mixpanel', 'mixpanel', 'analytics',
  '[{"type":"script_src","pattern":"cdn.mxpnl.com/libs/mixpanel","confidence":0.95},{"type":"resource_url","pattern":"api.mixpanel.com/track","confidence":0.98}]'::jsonb,
  array['US'], false),
('Amplitude', 'amplitude', 'analytics',
  '[{"type":"script_src","pattern":"cdn.amplitude.com","confidence":0.95},{"type":"resource_url","pattern":"api.amplitude.com","confidence":0.95}]'::jsonb,
  array['US'], false),
('Heap', 'heap', 'analytics',
  '[{"type":"script_src","pattern":"cdn.heapanalytics.com","confidence":0.95}]'::jsonb,
  array['US'], false),
('Hotjar', 'hotjar', 'analytics',
  '[{"type":"script_src","pattern":"static.hotjar.com","confidence":0.95},{"type":"resource_url","pattern":"hotjar.com/api","confidence":0.95}]'::jsonb,
  array['EU'], false),
('Clarity', 'microsoft-clarity', 'analytics',
  '[{"type":"script_src","pattern":"clarity.ms/tag","confidence":0.95}]'::jsonb,
  array['US'], false),
('Mouseflow', 'mouseflow', 'analytics',
  '[{"type":"script_src","pattern":"cdn.mouseflow.com","confidence":0.95}]'::jsonb,
  array['US'], false),
('Plausible', 'plausible', 'analytics',
  '[{"type":"script_src","pattern":"plausible.io/js/","confidence":0.95}]'::jsonb,
  array['EU'], false),

-- Marketing / Advertising
('Meta Pixel', 'meta-pixel', 'marketing',
  '[{"type":"script_src","pattern":"connect.facebook.net/en_US/fbevents.js","confidence":0.98},{"type":"resource_url","pattern":"facebook.com/tr","confidence":0.98}]'::jsonb,
  array['US'], false),
('Google Ads', 'google-ads', 'marketing',
  '[{"type":"script_src","pattern":"googleadservices.com","confidence":0.95},{"type":"resource_url","pattern":"googleads.g.doubleclick.net","confidence":0.95}]'::jsonb,
  array['US'], false),
('LinkedIn Insight', 'linkedin-insight', 'marketing',
  '[{"type":"script_src","pattern":"snap.licdn.com/li.lms-analytics/insight.min.js","confidence":0.98}]'::jsonb,
  array['US'], false),
('Twitter Pixel', 'twitter-pixel', 'marketing',
  '[{"type":"script_src","pattern":"static.ads-twitter.com/uwt.js","confidence":0.95}]'::jsonb,
  array['US'], false),
('TikTok Pixel', 'tiktok-pixel', 'marketing',
  '[{"type":"script_src","pattern":"analytics.tiktok.com/i18n/pixel","confidence":0.95}]'::jsonb,
  array['CN','US'], false),
('Pinterest Tag', 'pinterest-tag', 'marketing',
  '[{"type":"script_src","pattern":"s.pinimg.com/ct/core.js","confidence":0.95}]'::jsonb,
  array['US'], false),
('Snap Pixel', 'snap-pixel', 'marketing',
  '[{"type":"script_src","pattern":"sc-static.net/scevent","confidence":0.95}]'::jsonb,
  array['US'], false),
('Quora Pixel', 'quora-pixel', 'marketing',
  '[{"type":"script_src","pattern":"a.quora.com/qevents.js","confidence":0.95}]'::jsonb,
  array['US'], false),
('Reddit Pixel', 'reddit-pixel', 'marketing',
  '[{"type":"script_src","pattern":"www.redditstatic.com/ads/pixel.js","confidence":0.95}]'::jsonb,
  array['US'], false),

-- Marketing automation / CRM
('HubSpot', 'hubspot', 'marketing',
  '[{"type":"script_src","pattern":"js.hs-scripts.com","confidence":0.95},{"type":"script_src","pattern":"js.hsforms.net","confidence":0.95}]'::jsonb,
  array['US'], false),
('Mailchimp', 'mailchimp', 'marketing',
  '[{"type":"script_src","pattern":"chimpstatic.com","confidence":0.95}]'::jsonb,
  array['US'], false),
('Clevertap', 'clevertap', 'marketing',
  '[{"type":"script_src","pattern":"d2r1yp2w7bby2u.cloudfront.net","confidence":0.85},{"type":"script_src","pattern":"clevertap.com","confidence":0.95}]'::jsonb,
  array['IN','US'], false),
('WebEngage', 'webengage', 'marketing',
  '[{"type":"script_src","pattern":"cdn.webengage.com","confidence":0.95}]'::jsonb,
  array['IN'], false),
('MoEngage', 'moengage', 'marketing',
  '[{"type":"script_src","pattern":"cdn.moengage.com","confidence":0.95}]'::jsonb,
  array['IN'], false),

-- Personalisation
('Segment', 'segment', 'personalisation',
  '[{"type":"script_src","pattern":"cdn.segment.com/analytics.js","confidence":0.98}]'::jsonb,
  array['US'], false),
('Google Tag Manager', 'google-tag-manager', 'personalisation',
  '[{"type":"script_src","pattern":"googletagmanager.com/gtm.js","confidence":0.98}]'::jsonb,
  array['US'], false),
('Optimizely', 'optimizely', 'personalisation',
  '[{"type":"script_src","pattern":"cdn.optimizely.com","confidence":0.95}]'::jsonb,
  array['US'], false),
('VWO', 'vwo', 'personalisation',
  '[{"type":"script_src","pattern":"dev.visualwebsiteoptimizer.com","confidence":0.95}]'::jsonb,
  array['IN','US'], false),

-- Functional (never flagged as violation)
('Razorpay', 'razorpay', 'functional',
  '[{"type":"script_src","pattern":"checkout.razorpay.com/v1/checkout.js","confidence":0.99}]'::jsonb,
  array['IN'], true),
('Stripe', 'stripe', 'functional',
  '[{"type":"script_src","pattern":"js.stripe.com/v3","confidence":0.99}]'::jsonb,
  array['US'], true),
('PayU', 'payu', 'functional',
  '[{"type":"script_src","pattern":"jssdk.payu.in","confidence":0.98}]'::jsonb,
  array['IN'], true),
('reCAPTCHA', 'recaptcha', 'functional',
  '[{"type":"script_src","pattern":"google.com/recaptcha/api.js","confidence":0.99},{"type":"script_src","pattern":"gstatic.com/recaptcha","confidence":0.99}]'::jsonb,
  array['US'], true),
('Cloudflare Turnstile', 'cf-turnstile', 'functional',
  '[{"type":"script_src","pattern":"challenges.cloudflare.com/turnstile","confidence":0.99}]'::jsonb,
  array['US'], true),
('Intercom', 'intercom', 'functional',
  '[{"type":"script_src","pattern":"widget.intercom.io","confidence":0.95}]'::jsonb,
  array['US'], true),
('Freshchat', 'freshchat', 'functional',
  '[{"type":"script_src","pattern":"wchat.freshchat.com","confidence":0.95}]'::jsonb,
  array['IN','US'], true),
('Zendesk', 'zendesk', 'functional',
  '[{"type":"script_src","pattern":"zdassets.com/ekr","confidence":0.95}]'::jsonb,
  array['US'], true)

on conflict (service_slug) do update set
  service_name = excluded.service_name,
  category = excluded.category,
  detection_rules = excluded.detection_rules,
  data_locations = excluded.data_locations,
  is_functional = excluded.is_functional,
  version = tracker_signatures.version + 1,
  updated_at = now();
