import { createClient } from '@supabase/supabase-js'
import { notFound } from 'next/navigation'
import { composePrivacyNotice } from '@/lib/compliance/privacy-notice'

// Public privacy notice page — no auth required.
// Uses service role key to bypass RLS (the org id is part of the URL).

export default async function PrivacyNoticePage({
  params,
}: {
  params: Promise<{ orgId: string }>
}) {
  const { orgId } = await params

  const admin = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
  )

  const { data: org } = await admin
    .from('organisations')
    .select('name, compliance_contact_email, dpo_name')
    .eq('id', orgId)
    .single()

  if (!org) notFound()

  const { data: inventory } = await admin
    .from('data_inventory')
    .select('data_category, collection_source, purposes, legal_basis, retention_period, third_parties, data_locations')
    .eq('org_id', orgId)
    .order('data_category')

  const sections = composePrivacyNotice(org, inventory ?? [])

  return (
    <main className="max-w-3xl mx-auto px-6 py-12">
      <header className="mb-8 pb-6 border-b border-gray-200">
        <h1 className="text-3xl font-bold">Privacy Notice</h1>
        <p className="mt-2 text-sm text-gray-600">
          {org.name} · Compliant with the Digital Personal Data Protection Act 2023
        </p>
      </header>

      <article className="space-y-8">
        {sections.map((section, i) => (
          <section key={i}>
            <h2 className="text-lg font-semibold mb-2">
              {i + 1}. {section.heading}
            </h2>
            <div className="text-sm text-gray-700 whitespace-pre-line leading-relaxed">
              {section.body}
            </div>
          </section>
        ))}
      </article>

      <footer className="mt-12 pt-6 border-t border-gray-200 text-xs text-gray-500">
        <p>
          This notice was generated by ConsentShield. Visit{' '}
          <a
            href="https://consentshield.in"
            className="underline"
            target="_blank"
            rel="noopener noreferrer"
          >
            consentshield.in
          </a>{' '}
          for more information.
        </p>
      </footer>
    </main>
  )
}
